### ISSUE TITLE
RootRevoke and logging

### ISSUE THREAD

**Issue by pghmcfc** [proftpd/proftpd#1001]
I'm trying 1.3.7rc3 and all seems OK so far functionally.

One thing I did notice though was that my daily logwatch report has quite a lot of references to entries like:
```
Apr 28 20:22:16 ****** proftpd[703051]: 2020-04-28 20:22:16,804 ***** proftpd[1654993] **** (*****[ipv6 addr]): RootRevoke in effect, dropped root privs
```
These happen for both anonymous and regular users. I was wondering whether these lines were really worthy of being visible at the default log level? If you think they are, that's fine and I'll take it to logwatch instead and get rid of them from the daily report there.

On a possibly-related note, for authenticated users (using PAM), I'm also getting these:
```
Apr 28 20:22:18 ftpserver proftpd[703051]: 2020-04-28 20:22:18,806 ftpserver.city-fan.org proftpd[1654993] ftpserver.city-fan.org (client.city-fan.org[2001:...::24]): USER paul: Login successful.
Apr 28 20:22:22 ftpserver proftpd[703051]: 2020-04-28 20:22:22,814 ftpserver.city-fan.org proftpd[1654993] ftpserver.city-fan.org (client.city-fan.org[2001:...::24]): ROOT PRIVS: unable to seteuid(): Operation not permitted
Apr 28 20:22:22 ftpserver proftpd[703051]: 2020-04-28 20:22:22,814 ftpserver.city-fan.org proftpd[1654993] ftpserver.city-fan.org (client.city-fan.org[2001:...::24]): ROOT PRIVS: unable to setegid(): Operation not permitted
Apr 28 20:22:22 ftpserver proftpd[703051]: 2020-04-28 20:22:22,820 ftpserver.city-fan.org proftpd[1654993] ftpserver.city-fan.org (client.city-fan.org[2001:...::24]): RELINQUISH PRIVS: unable to seteuid(PR_ROOT_UID): Operation not permitted
Apr 28 20:22:22 ftpserver proftpd[703051]: 2020-04-28 20:22:22,823 ftpserver.city-fan.org proftpd[1654993] ftpserver.city-fan.org (client.city-fan.org[2001:...::24]): FTP session closed.
```
The "Operation not permitted" responses don't seem to prevent anything from working. I guess these must be capability or SELinux checks that are causing them, though there are no audit messages to suggest it's an SELinux issue (though they could be dontaudit-ed). If these are expected in normal operation, it'd be nice not to see them in the log.

**Comment by Castaglia** [comment]
The `RootRevoke` messages are there because the default settings were changed by [Bug #4241](http://bugs.proftpd.org/show_bug.cgi?id=4241), done in 1.3.7rc1.  Since 1.3.7 hasn't had a full release yet (hopefully soon), I wanted to make sure admins saw the change in behavior in the logs.  That _said_, we could change the logging level to be _e.g._ debug level 1 or 2, so that it doesn't necessarily show up by default.

The `ROOT_PRIVS` macro is used in quite a few places in the code, and in modules, for requesting root permissions for some operations.  Depending on the runtime configuration, those root permissions may not be accessible.  A best practice is to handle any errors, even if only by logging.  These log messages, too, can probably be reduced in verbosity so that they are still logged, just not by default.

**Comment by Castaglia** [comment]
This should now be better for default logging in `master`.
