### ISSUE TITLE
Separate xferlog for TLS connections

### ISSUE THREAD

**Issue by xjobex** [proftpd/proftpd#1035]
In our environment we set `TLSRequired off` to allow also non-TLS client to connect to our server. Is it possible to have two separate xferlogs, one for clients that are using TLS and one for clients who do not use it? We are using a single VirtualHost.

**Comment by Castaglia** [comment]
Currently it does not look like ProFTPD makes this easy.  The `<IfUser>` sections supported by the `mod_ifsession` module might look like they would work -- except that the `TransferLog` is opened _during_ the authentication phase (although I'm not sure why), and `mod_ifsession` hooks would only run _after_ authentication.

Could you create a custom `LogFormat`, and include the `%{protocol}` variable -- so that each line would have "ftps" (for your TLS-using clients), or "ftp" (for non-TLS)?

**Comment by xjobex** [comment]
Thank you for the `%{protocol}` hint, it solved our problem.

**Comment by Castaglia** [comment]
Excellent, glad to hear that you found a solution.
