### ISSUE TITLE
SFTP: No other authentication mechanisms available / SFTPCompression delayed strange behaviour

### ISSUE THREAD

**Issue by cedef** [proftpd/proftpd#1060]
### What I Did

Using sFTP client Filezilla version >=3.48, I'm getting the following error when trying to connect to Proftpd 1.3.6 using the following user `dummyxyz` (no matter the password, the account does not need to exist).

```
Status:	Using username "dummyxyz". 
Command:	Pass: ********************
Error:	FATAL ERROR: Remote side sent disconnect message
Error:	type 14 (no more auth methods available):
Error:	"No other authentication mechanisms available"
Error:	Could not connect to server
```

But, If I'm trying with username `dummyxy`, I'm getting an _authentication error_ (which is expected)
```
Status:	Using username "dummyxy". 
Status:	Access denied 
Error:	Authentication failed.
Error:	Critical error: Could not connect to server
```

### What I Expected/Wanted

I was expecting same error with 2 (slightly) different usernames.
By digging around, I've been able to establish that 
* 1.3.7 version gives the same result
* SFTPAuthMethods has to be set to `password`
* _without_ the customization `SFTPCiphers` , `SFTPKeyExchanges` and `SFTPDigests` proftpd works as expected.
* _with_ the customization `SFTPCiphers` , `SFTPKeyExchanges` and `SFTPDigests` *and* `SFTPCompression` set to `on` proftpd works as expected.
* with version of Filezilla Client < 3.48 proftpd works as expected

Would it be possible that somehow, compression is messing arround with some data payload which _could_ explain why depending on the username, we don't have the same behaviour ?

### ProFTPD Version and Configuration

Please find attached output of `proftpd -V` and the `proftpd.conf` file

[proftpd-version.txt](https://github.com/proftpd/proftpd/files/4966199/proftpd-version.txt)
[proftpd.conf.txt](https://github.com/proftpd/proftpd/files/4966202/proftpd.conf.txt)

IMHO, here is the relevant part of the configuration:
```
SFTPCiphers aes128-ctr aes192-ctr aes256-ctr
SFTPKeyExchanges diffie-hellman-group18-sha512 diffie-hellman-group16-sha512 diffie-hellman-group14-sha256 diffie-hellman-group-exchange-sha256
SFTPDigests hmac-sha2-256 hmac-sha2-512 umac-64@openssh.com umac-128@openssh.com

SFTPAuthMethods password
SFTPCompression delayed
```

A [bugreport](https://trac.filezilla-project.org/ticket/12218#ticket) has also been sent to Filezilla, as it seems the bug is possible when we use both Proftpd specific configuration _and_ specific Filezilla sftp client version.

Let me know if you need more information, I'll help digging arround !

**Comment by Castaglia** [comment]
Would it be possible for you to try a new ProFTPD release, _e.g._ 1.3.6e, or 1.3.7a?  I believe this may be the same issue as [Bug #4385](http://bugs.proftpd.org/show_bug.cgi?id=4385), which should be fixed in those newer versions.

**Comment by cedef** [comment]
Indeed it looks very similar, but as I said, I've also reproduced with release `1.3.7` 

Regards,

**Comment by Castaglia** [comment]
Can you provide the `SFTPLog` generated for this error, please?   And accomanying SFTP tracing?  For example, use:
```
SFTPLog /path/to/proftpd-sftp.log
TraceLog /path/to/proftpd-sftp.log
Trace ssh2:20 sftp:20
```

**Comment by Castaglia** [comment]
Also, for the usernames you are using, which one is valid/exists (if any)?  The original description does not indicate whether one of them is a valid account or not.

**Comment by tstangner** [comment]
This has nothing to with the SSH_MSG_IGNORE issue @Castaglia - I stumbled upon the same bug/problem and tried to debug the issue. I am no C expert, but I think I understand enough to pinpoint the problem.

When using ProFTPD 1.3.6b/c/d and FileZilla 3.48/3.49 and using password authentication via SFTP I get the follwing error in FIleZilla, but _only_ with specific username lengths (like @cedef ):

`FATAL ERROR: No supported authentication methods available`

The ProFTPD SFTP logfile on the server yields:

```
2020-08-03 18:11:58,988 mod_sftp/1.0.0[3942]: sent server version 'SSH-2.0-mod_sftp'
2020-08-03 18:11:58,988 mod_sftp/1.0.0[3942]: received client version 'SSH-2.0-FileZilla_3.49.1'
2020-08-03 18:11:58,988 mod_sftp/1.0.0[3942]: handling connection from SSH2 client 'FileZilla_3.49.1'
2020-08-03 18:11:59,027 mod_sftp/1.0.0[3942]:  + Session key exchange: curve25519-sha256@libssh.org
2020-08-03 18:11:59,027 mod_sftp/1.0.0[3942]:  + Session server hostkey: ssh-rsa
2020-08-03 18:11:59,027 mod_sftp/1.0.0[3942]:  + Session client-to-server encryption: aes256-ctr
2020-08-03 18:11:59,027 mod_sftp/1.0.0[3942]:  + Session server-to-client encryption: aes256-ctr
2020-08-03 18:11:59,027 mod_sftp/1.0.0[3942]:  + Session client-to-server MAC: hmac-sha2-256
2020-08-03 18:11:59,027 mod_sftp/1.0.0[3942]:  + Session server-to-client MAC: hmac-sha2-256
2020-08-03 18:11:59,028 mod_sftp/1.0.0[3942]:  + Session client-to-server compression: none
2020-08-03 18:11:59,028 mod_sftp/1.0.0[3942]:  + Session server-to-client compression: none
2020-08-03 18:11:59,108 mod_sftp/1.0.0[3942]: sending acceptable userauth methods: publickey,password
2020-08-03 18:11:59,137 mod_sftp/1.0.0[3942]: client sent SSH_MSG_IGNORE message (99 bytes)
2020-08-03 18:11:59,138 mod_sftp/1.0.0[3942]: cipher algorithm 'USERAUTH_REQUEST XXYYZZ_0' or MAC algorithm 'none' unacceptable for password authentication, denying password authentication request
2020-08-03 18:11:59,138 mod_sftp/1.0.0[3942]: sending userauth failure; remaining userauth methods: publickey
2020-08-03 18:11:59,170 mod_sftp/1.0.0[3942]: disconnecting client (received EOF)
```

Pay attention to the cipher algorithm line, where 'USERAUTH_REQUEST USERNAME PASSWORD' gets logged as cipher (and MAC 'none' which can't be the case, since hmac-sha2-256 has been negotiated).

As mentioned above the issue _only _ happens with specific username lengths. Also, the configured SFTP options have an impact - if you strip some cipher or mac algorithms from the configuration, logins may suddenly be possible.

My first thought after discovering this was 'memory handling/corruption problem' so i tried to debug the issue.

```
auth-passwd.c:

  cipher_algo = sftp_cipher_get_read_algo();
  mac_algo = sftp_mac_get_read_algo();

  if (strncmp(cipher_algo, "none", 5) == 0 ||
      strncmp(mac_algo, "none", 5) == 0) {
```

sftp_auth_password() gets the cipher and mac algos from sftp_cipher_get_read_algo() (and sftp_mac_get_read_algo() respectively)  and verifies them. This is where the above error is generated in the log file.

The pointers to the ciper/mac algorithm strings are stored in static arrays in cipher.c and mac.c (and sftp_xxx_get_read_algo() returns those pointers).

The pointers are set via:

```
int sftp_cipher_set_read_algo(const char *algo) {
  unsigned int idx = read_cipher_idx;
  size_t key_len = 0, discard_len = 0;
[...]
  read_ciphers[idx].algo = algo;
```

and this function gets called by setup_c2s_encrypt_algo(struct sftp_kex *kex, const char *algo), which in turn gets called by get_session_names() in kex.c:

```
static int get_session_names(struct sftp_kex *kex, int *correct_guess) {
  const char *kex_algo, *shared, *client_list, *server_list;
  const char *client_pref, *server_pref;
  pool *tmp_pool;
[...]
  shared = sftp_misc_namelist_shared(kex->pool, client_list, server_list);
  if (shared) {
    if (setup_c2s_encrypt_algo(kex, shared) < 0) {
      destroy_pool(tmp_pool);
      return -1;
    }
```

Backtracking further, get_session_names() gets called by sftp_kex_handle():

```
int sftp_kex_handle(struct ssh2_packet *pkt) {
  int correct_guess = TRUE, res, sent_newkeys = FALSE;
  char mesg_type;
  struct sftp_kex *kex;
[...]
  if (get_session_names(kex, &correct_guess) < 0) {
    destroy_kex(kex);
    return -1;
  }
[...]
  destroy_kex(kex);
  return 0;
}
```

So, the string for the cipher (and mac) algorithm is allocated in the kex pool and this pointer is passed down to sftp_cipher_set_read_algo() and stored there.
The problem is, that kex gets destroyed after the key exchange took place, this includes freeing the string pointers, which in turn means, that now the structs in cipher.c and mac.c hold pointers to already freed memory.

If you are lucky, this memory does not get used/overwritten/reallocated by other pool allocations, if not, the pointers to the cipher/mac algos contain garbage and/or parts of other strings, which explains why the username got logged as cipher in the SFTP log file. If the nullterm int this area gets overwritten, your logfile may contain sensitive data from other memory areas, other exploits may be possible (haven't checked).

My proposed fix for this is to allocate/free the string space in cipher.c/mac.c separately, but I am not really familiar with the ProFTPD memory handling, perhaps it would be better to use a separate/other pool for the allocations (rather than allocating/freeing directly via strdup()/free()):

```
--- contrib/mod_sftp/cipher.c.org	2020-02-19 03:35:47.000000000 +0100
+++ contrib/mod_sftp/cipher.c	2020-08-05 02:31:27.774515449 +0200
@@ -32,7 +32,7 @@
 #include "interop.h"
 
 struct sftp_cipher {
-  const char *algo;
+  char *algo;
   const EVP_CIPHER *cipher;
 
   unsigned char *iv;
@@ -150,6 +150,10 @@
   }
 
   cipher->cipher = NULL;
+
+  if (cipher->algo) {
+    free(cipher->algo);
+  }
   cipher->algo = NULL;
 }
 
@@ -387,7 +391,12 @@
       (unsigned long) discard_len);
   }
 
-  read_ciphers[idx].algo = algo;
+  read_ciphers[idx].algo = strdup(algo);
+  if (read_ciphers[idx].algo == NULL) {
+    (void) pr_log_writefile(sftp_logfd, MOD_SFTP_VERSION,
+      "memory allocation error");
+    return -1;
+  }
   read_ciphers[idx].key_len = (uint32_t) key_len;
   read_ciphers[idx].discard_len = discard_len;
   return 0;
@@ -585,7 +594,12 @@
       (unsigned long) discard_len);
   }
 
-  write_ciphers[idx].algo = algo;
+  write_ciphers[idx].algo = strdup(algo);
+  if (write_ciphers[idx].algo == NULL) {
+    (void) pr_log_writefile(sftp_logfd, MOD_SFTP_VERSION,
+      "memory allocation error");
+    return -1;
+  }
   write_ciphers[idx].key_len = (uint32_t) key_len;
   write_ciphers[idx].discard_len = discard_len;
   return 0;
--- contrib/mod_sftp/mac.c.org	2020-02-19 03:35:47.000000000 +0100
+++ contrib/mod_sftp/mac.c	2020-08-05 02:31:41.570375166 +0200
@@ -34,7 +34,7 @@
 #include "umac.h"
 
 struct sftp_mac {
-  const char *algo;
+  char *algo;
   int algo_type;
 
   const EVP_MD *digest;
@@ -173,6 +173,10 @@
   }
 
   mac->digest = NULL;
+
+  if (mac->algo) {
+    free(mac->algo);
+  }
   mac->algo = NULL;
 }
 
@@ -689,7 +693,13 @@
     return -1;
   }
 
-  read_macs[idx].algo = algo;
+  read_macs[idx].algo = strdup(algo);
+  if (read_macs[idx].algo == NULL) {
+    (void) pr_log_writefile(sftp_logfd, MOD_SFTP_VERSION,
+      "memory allocation error");
+    return -1;
+  }
+
   if (strncmp(read_macs[idx].algo, "umac-64@openssh.com", 12) == 0) {
     read_macs[idx].algo_type = SFTP_MAC_ALGO_TYPE_UMAC64;
     umac_read_ctxs[idx] = umac_alloc();
@@ -822,7 +832,13 @@
     return -1;
   }
 
-  write_macs[idx].algo = algo;
+  write_macs[idx].algo = strdup(algo);
+  if (write_macs[idx].algo == NULL) {
+    (void) pr_log_writefile(sftp_logfd, MOD_SFTP_VERSION,
+      "memory allocation error");
+    return -1;
+  }
+
   if (strncmp(write_macs[idx].algo, "umac-64@openssh.com", 12) == 0) {
     write_macs[idx].algo_type = SFTP_MAC_ALGO_TYPE_UMAC64;
     umac_write_ctxs[idx] = umac_alloc();
```

**Comment by tstangner** [comment]
I opened a bug report for this issue in the bugtracker: http://bugs.proftpd.org/show_bug.cgi?id=4401

**Comment by Castaglia** [comment]
@tstangner thank you for the thorough analysis, and for tracking down this bug!  I'll be working on this issue today, and hopefully with have a PR to address this shortly.

**Comment by Castaglia** [comment]
https://github.com/proftpd/proftpd/pull/1081 is my proposed patch/fix for this.

**Comment by tstangner** [comment]
Looks good @Castaglia , using a separate pool for the allocations is more in line with the rest of the memory handling in ProFTPD - I tested versions 1.3.6e and 1.3.7a with your patch applied and could not reproduce the login issues.

**Comment by Castaglia** [comment]
@cedef I've merged the above PR into master; can you try it out, see if it addresses your issues as well?

**Comment by cedef** [comment]
Thank you for that quick troubleshoot and fix !
I'll check that out soon and I'll come back to you.

**Comment by cedef** [comment]
I can confirm that with commit 7922c2893df29c313e215948db17b346459817bf I can reproduce the bug, while with a proftpd built on commit cca8b70c6abb1c59476eef293a1059c81c8c52c1 it works fine.

Again, thank you to @tstangner  for the troubleshoot and to @Castaglia for the merged PR.

**Comment by marcin-gryszkalis** [comment]
fyi, I applied the patch for this problem https://github.com/proftpd/proftpd/commit/2913db8ed4e3f570e75e3679aa0b447c73f7d38a.patch 
to vanilla 1.3.7a and it worked. In my case the problem appeared in proftpd.log as
```
USER xxx (Login failed): cipher algorithm 'none' or MAC algorithm 'one' unsupported for password authentication
USER yyy (Login failed): cipher algorithm 'none' or MAC algorithm 'none' unsupported for password authentication
```
(when in fact negotiated ciphers/macs were proper)

**Comment by www-haifeng** [comment]
![1656593353246](https://user-images.githubusercontent.com/42060300/176680891-1c7f3630-c99b-47ce-ba17-c2e12ec681c2.png)
