### ISSUE TITLE
Update TLS minimum supported DH parameter size to 2048

### ISSUE THREAD

**Issue by bratkartoffel** [proftpd/proftpd#1101]
Hi,

it seems proftpd mod_sftp and mod_tls supports DH-params with size < 2048. Many recommendations (e.g. NIST or BSI) suggest / require using sizes > 2000.
Can you please remove the 512-bit, 1024-bit and 1536-bit groups? For mod_tls, can you please add parameters for 3072 and 4096 too?

https://github.com/proftpd/proftpd/blob/7ef40b03eae22e60a9a91a74b4043eb15dbe53c1/contrib/mod_sftp/dhparams.pem#L13
https://github.com/proftpd/proftpd/blob/7ef40b03eae22e60a9a91a74b4043eb15dbe53c1/contrib/mod_tls.c#L163

https://weakdh.org/sysadmin.html
https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-2.pdf?__blob=publicationFile (Page 18)
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf (Page 15)

I see that the params may be configured externally using http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPDHParamFile, but including secure defaults should also fine too.

Thanks,
Simon

**Comment by Castaglia** [comment]
You can see [here](https://github.com/proftpd/proftpd/blob/master/contrib/mod_tls.c#L492), for mod_tls, why the default minimum DH size is 1024 -- with an optional ability to disable that minimum size.  That's why the shorter DH params for mod_tls are still present.  Adding some defaults for 3072/4096 seems reasonable.

Similarly, mod_sftp has a minimum DH size of 2048 (see [here](https://github.com/proftpd/proftpd/blob/master/contrib/mod_sftp/kex.c#L49)) by default, with an option to allow shorter DHs if needed.

**Comment by bratkartoffel** [comment]
mod_tls:
For Java this is no longer correct, Oracle published updates on 2018-01-16, enabling DH-Parameters with at least 2048 for all JRE versions including 6. So every supported java version now supports better params.
https://www.java.com/en/jre-jdk-cryptoroadmap.html

So I think setting the default to 2048 (matching mod_sftp) should be reasonable now.

mod_sftp:
Wow, I haven't seen this constant, nor the setting so far. Thanks for showing, that really looks fine.

**Comment by Castaglia** [comment]
Fixed in master.
