### ISSUE TITLE
Cannot disable client-initiated renegotiation for FTPS

### ISSUE THREAD

**Issue by azurit** [proftpd/proftpd#1119]
### What I Did

Client-initiated renegotiation for FTPS is enabled by default and i can't see a way how to disable it. Can be checked, for example, using this tool:
https://www.immuniweb.com/ssl/

### What I Expected/Wanted

Should not be enabled by default or, at least, there should be a way how to disable it (i only found a way how to enable it using TLSOptions but i don't really understand it, as it's enabled by default).

### ProFTPD Version and Configuration

1.3.6, Debian Buster, sorry i can't test newer version.

**Comment by Castaglia** [comment]
This related to Issue #1076; client-initiated renegotiations were _unexpectedly_ allowed, and fixed by https://github.com/proftpd/proftpd/commit/ae4203882ccb7eed6adf8c9c1e34b47289eb0c0c.  This fix will be in the next 1.3.7 maintenance release, and next 1.3.8 RC, but not backported to the 1.3.6 branch.
