### ISSUE TITLE
Rehash Passwordhashes to migrate from MD5 to SHA2

### ISSUE THREAD

**Issue by bogi0704** [proftpd/proftpd#1228]
Hi there,

I am currently using mod_auth_file.c (AuthUserFile) to store the hashes of my users. I was using MD5 and a random salt to create the hashes, for example:

$1$L+sGe2zB$5.cXgMWq/Y9AoP2A4mIPN0

I want to migrate to SHA2-512 in the future so I tried to take the above MD5 hash as the input for the new SHA2-512 hash, but that does not work. You mentioned that mod_auth_file.c does not interpret the output but rather just sends it all to the crypt(3) library for comparison.

You mentioned that there might be a way to create a new module which would do just that:
> there might be a way to auto-generate new password hashes, but it would require a custom module, and building
> ProFTPD from source.  If you think you may need to explore this route, please contact me directly via email.
_Originally posted by @Castaglia in https://github.com/proftpd/proftpd/issues/982#issuecomment-618735492_

That is something I would really need and appreciate if you could look into this.

Thanks!

**Comment by Castaglia** [comment]
In order to implement an automatic conversion from older-to-newer password hashes in a module, that module would need to be do the following:
* Read from multiple `AuthUserFile` files, old and new
* Write new converted entries to the new `AuthUserFile`

This use case may also apply to SQL-based user password entries as well.

Another consideration is knowing "when to stop", how to deal with the long tail of users who may not log in frequently, and thus may not be automatically converted.

@bogi0704 What Unix distribution/version are you using?  I ask because SHA-512 support in `crypt(3)` is very modern; not all `crypt(3)` implementations support it.  So knowing your Unix version/distribution will help me use a local development setup that matches your environment.

**Comment by bogi0704** [comment]
Thanks for looking into this!

I am using proftpd on different OS Versions. Older ones like SLES 11 SP4 and CentOS 6, but I am migrating to SLES 15 and CentOS 7. It does take time though.

If SHA2-512 compatibility is an issue, then SHA2-256 should suffice imho.

Does the module really need to create a separate `AuthUserFile` ? I was thinking that exchanging the hash inside the current `AuthUserFile` would work too. This may prevent the hassle of looking up Users in different files.

The "when to stop" question is interesting. From the enhancement/module perspective this would likely never stop. But I as an admin may decide that a defined grace period should be enough after which I would deactivate this module again. Everyone who logs in afterwards would have to request a new password manually.

**Comment by Castaglia** [comment]
The reason to have two separate `AuthUserFile` files, one old and one new, is to better separate which users have updated password hashes, and which do not.  (And because doing in-place edits in a file, from C code, is _really_ not a lot of fun.  The new password hash values will be longer, which makes shifting all bytes around in the entire file to expand a segment in the middle.)

I'm envisioning that this password-rehashing module would not _replace_ `mod_auth_file`, in terms of actually doing the authenticating of users.  Instead, the password rehashing would happen as part of a preprocessing step of a `PASS` command.  This way, you would configure `mod_auth_file` to use only the "new" `AuthUserFile`, and configure the rehashing module with both old and new files.  Something like:
```
<IfModule mod_passwd_update.c>
  PasswordUpdateEngine one
  PasswordUpdateLog /path/to/proftpd.log

  # List of password hashing algorithms, in preference orde
  PasswordUpdateAlgorithms sha2-512 sha2-256 ...

  PasswordUpdateFiles /path/to/ftpd.passwd.old /path/to/ftpd.passwd.new
</IfModule>

AuthUserFile /path/to/ftpd.passwd.new
```

**Comment by Castaglia** [comment]
I've written a module to do this; see https://github.com/Castaglia/proftpd-mod_passwd_update.

**Comment by bogi0704** [comment]
Thank you very much for this! I will build the module and perform some tests, see if everything is fine.
I never hoped for such a quick implementation 😅

**Comment by bogi0704** [comment]
Good news! I have tested the module and works. But I have noticed that it only works with plain ftp, not sftp:

`sftp -oPort=2422 testuser@10.6.0.102

==> proftpd_system_log <==
2021-05-17 16:40:04,743 servername proftpd[44354] 10.6.0.102 (10.6.0.102[10.6.0.102]): USER testuser: no such user found from 10.6.0.102 [10.6.0.102] to 10.6.0.102:2422

==> sftp_log <==

==> trace_log <==
2021-05-17 16:40:09,625 [44354] <passwd_update:9>: skipping password migration for ssh2 protocol session`

would you be able to add that, and possibly ftps as well? I did not test ftps since we are not using it that much...

**Comment by Castaglia** [comment]
Yes, I didn't implement support for SFTP sessions yet; that protocol is more convoluted/involved, thus I'm specifically excluding that, for now.  I might have time to look into this support later tonight.

FTPS logins should be handled by `mod_passwd_update`, as they are essentially the same as plain FTP.

**Comment by Castaglia** [comment]
The `mod_passwd_update` module now handles password-based SSH logins properly.

**Comment by bogi0704** [comment]
I have tested the module just now. As you said, it works with password-based SSH logins!
The issue I am facing now while testing is using publickey-based SSH logins. If a user has an old hash and is using publickey-based SSH login, the user will be prompted for a password. This is an issue because there are many scripts that are authenticating this way. Any script would get stuck at that point. Hmm.
Can you create a flag an admin can set to enable and disable this behaviour? This way I can decide whether it is time to force a migration or not.

But maybe there is a better solution for this?

**Comment by Castaglia** [comment]
Two possible approaches come to mind.

First, you could use a configuration like this, for your SFTP `<VirtualHost>`:
```
<IfModule mod_passwd_update.c>
  PasswordUpdateEngine on
  PasswordUpdateLog /path/to/proftpd.log

  # List of password hashing algorithms, in preference orde
  PasswordUpdateAlgorithms sha2-512 sha2-256 ...

  PasswordUpdateFiles /path/to/ftpd.passwd.old /path/to/ftpd.passwd.new
</IfModule>

AuthUserFile /path/to/ftpd.passwd.old
```
With this, we have `mod_passwd_update` _opportunistically_ updating password hashes -- but the updated password hashes are not _actually_ being used by `mod_auth_file`.  This way, the non-password-using clients won't be prompted (since they'll continue using their existing entries in the old `AuthUserFile`).  Then you would have to compare the old and new `AuthUserFile` entries yourself, and have to track down the non-updated user entries (these scripted, publickey-based logins) yourself.

Alternatively, I implement some kind of "ignore these users" directive for `mod_passwd_update`, and you explicitly configure a list of usernames that `mod_passwd_update` should *not* try to update.

**Comment by bogi0704** [comment]
Is there a way to use mod_ifsession and a Class to identify logins via public key? That way I could define a Class with public key authentication sessions and setup the Module the same as you said above. In every other case the normal global setup should work.

I have tested the module and apart from this "problem" it works fine. Thank you!

**Comment by Castaglia** [comment]
Unfortunately not; classes are defined by client source IPs/DNS, not by the client authentication methods.  Publickey-based logins are specific to SSH (and thus to `mod_sftp`), not generally applicable.

**Comment by Castaglia** [comment]
@bogi0704 since the current module meets most of the requested needs, I'm going to close this ticket.  Any future work/discussions can be done with tickets associated with that module's GitHub repo:
* https://github.com/Castaglia/proftpd-mod_passwd_update

Thanks!
