### ISSUE TITLE
TCP keepalive SocketOptions should apply to control as well as data connection

### ISSUE THREAD

**Issue by cus** [proftpd/proftpd#1402]
Only the data connection is set up using the fine grained keepalive settings. This is bad, because keepalive actually makes sense for the control connection.

**Comment by Castaglia** [comment]
Thanks for this report.  Could you provide the `proftpd -V` output, and the exact `SocketOptions` configuration that you are using, so that I can reproduce this locally?  It was also help me if you could provide the contents of the `/etc/os-release` file; different platforms have different levels of TCP keepalive support.

**Comment by cus** [comment]
I actually tested an older version, but now I tried it with 1.3.6e on OpenSuSE Leap 15.3 x86_64.

A good way to test it is to set the following options:

`SocketOptions keepalive 60:9:75`

Which does not work on vanialla proftpd, because of issue #1401. But if you fix that, then you can monitor ther control connection with Wireshark and check that no keepalives are sent in the control connection every 60 seconds.

**Comment by cus** [comment]
[proftpd-v.txt](https://github.com/proftpd/proftpd/files/8306524/proftpd-v.txt)

**Comment by Castaglia** [comment]
This should now be fixed in master, and backported to the 1.3.7 branch.  Thanks!
