### ISSUE TITLE
Permission question about proftpd.sock

### ISSUE THREAD

**Issue by chengyechun** [proftpd/proftpd#1784]
In the code, I see that the permission of proftpd.sock is 0777. I'm curious in what scenario such a high permission is needed. Usually this sock permission is 0755, so is 0777 too high?
![image](https://github.com/proftpd/proftpd/assets/57088250/b9197804-3322-46fc-8977-7046cabdea90)

**Comment by Castaglia** [comment]
This Unix domain socket is used for communicating with the running ProFTPD process via messages, and the `mod_ctrls` module.  ProFTPD's Controls system has a built-in set of ACLs which actually govern who (by user/group) can perform which actions (by name); see:
* http://www.proftpd.org/docs/howto/Controls.html

Thus the Controls ACLs provide finer-grained support that Unix filesystem permissions.  These ACLs also require that all permissions be explicitly granted.

Rather than having to instruct users/admins on how to debug `ftpdctl` permission issues which might arise from a combination of Unix filesystem permissions and Controls ACLs, I decided to remove the Unix filesystem permissions from the picture (since they are not adding anything), and allow any process to connect/read/write to that Unix domain socket.
