### ISSUE TITLE
list: invalid command

### ISSUE THREAD

**Issue by mmiat** [proftpd/proftpd#179]
Hi
I've Debian 7.9 with proftpd 1.3.4a-5+deb7u3, and when I connect with FileZilla I've no problem, but when using ftp from bash I connect successfully but I can't use command "list", I receive "invalid command error". "ls" works fine. my problem is that php seems to using "list", not "ls", so my scripts don't work

**Comment by Castaglia** [comment]
The "invalid command error" is probably coming from the `ftp` binary itself, not from proftpd.

The FTP command for listing directories is `LIST`, but many FTP clients, in order to look more shell-like, present this to you (the user) as "ls".  But other FTP clients/libraries (such as, perhaps, PHP) provide it as "list", rather than "ls".

But as far as I can tell, this is more of a client issue than a server issue.

**Comment by mmiat** [comment]
using "TLSOptions NoSessionReuseRequired" as you suggested in another issue thread fixes my problem, now I can list all files and folders, but when I try to access one of them a popup appears ("unable to accesso ./folder") and pressing OK doesn't close it

**Comment by Castaglia** [comment]
Popups are handled by the client/browser; they are not something that can be controlled/configured by ProFTPD.

**Comment by Castaglia** [comment]
I'd like to close this, as the original `LIST` issue was fixed.  Any objections?

**Comment by mmiat** [comment]
ok
