### ISSUE TITLE
Can´t upload/ delete/ rename lib folders

### ISSUE THREAD

**Issue by ianklemm** [proftpd/proftpd#216]
Hello,

I can´t upload, delete or rename folders, called "lib".
If i rename the folder to "lib1" or something like that, i have no problems.

**Comment by Castaglia** [comment]
This happens because your FTP session is chrooted; this means that "/lib" (and "/etc") can potentially have special meanings/purposes, and are thus _guarded_ by the `mod_rlimit` module.  To disable this guarding, see the [`RLimitChroot`](http://www.proftpd.org/docs/modules/mod_rlimit.html#RLimitChroot) directive docs.

**Comment by ianklemm** [comment]
Thank you!
