### ISSUE TITLE
PID file /run/proftpd/proftpd.pid not readable (yet?) after start

### ISSUE THREAD

**Issue by kunkinkan** [proftpd/proftpd#341]
### What I Did

Newly installed centos with virtualmin. Tried to start proftpd. It did not start.
### Output

```
[root@host /]# systemctl status proftpd.service
● proftpd.service - ProFTPD FTP Server
   Loaded: loaded (/usr/lib/systemd/system/proftpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: resources) since Thu 2016-10-06 13:34:54 UTC; 21s ago
  Process: 8418 ExecStart=/usr/sbin/proftpd $PROFTPD_OPTIONS (code=exited, status=0/SUCCESS)

Oct 06 13:34:46 host systemd[1]: Starting ProFTPD FTP Server...
Oct 06 13:34:54 host systemd[1]: PID file /run/proftpd/proftpd.pid not readable (yet?) after start.
Oct 06 13:34:54 host systemd[1]: proftpd.service never wrote its PID file. Failing.
Oct 06 13:34:54 host systemd[1]: Failed to start ProFTPD FTP Server.
Oct 06 13:34:54 host systemd[1]: Unit proftpd.service entered failed state.
Oct 06 13:34:54 host systemd[1]: proftpd.service failed.

```
### ProFTPD Version and Configuration

`ProFTPD Version 1.3.5a
`

No changes made to configuration file.

/run/proftpd contains:

```
[root@host proftpd]# ls
proftpd.delay  proftpd.scoreboard  proftpd.scoreboard.lck  proftpd.sock

```

**Comment by Castaglia** [comment]
If you look in your `proftpd.conf`, does it have a `PidFile` directive?  If so, what file/path is configured for that `PidFile` (_i.e._ does it match that `/run/proftpd/proftpd.pid` path that `systemd` is expecting)?  If not, then what does `proftpd -V` show?

**Comment by Castaglia** [comment]
There's been no further information on this ticket; as such, I'm going to close it.  Please re-open with the requested information.

**Comment by bzadhere** [comment]
the same problem happened to me.

[root@zhangbb ~]# systemctl status proftpd
● proftpd.service - ProFTPD FTP Server
   Loaded: loaded (/usr/lib/systemd/system/proftpd.service; disabled; vendor preset: disabled)
   Active: failed (Result: resources) since Wed 2019-01-16 14:51:48 CST; 10min ago
  Process: 2223 ExecStart=/usr/sbin/proftpd $PROFTPD_OPTIONS (code=exited, status=0/SUCCESS)

Jan 16 14:51:48 zhangbb systemd[1]: Starting ProFTPD FTP Server...
Jan 16 14:51:48 zhangbb systemd[1]: PID file /run/proftpd/proftpd.pid not readable (yet?) after start.
Jan 16 14:51:48 zhangbb systemd[1]: proftpd.service never wrote its PID file. Failing.
Jan 16 14:51:48 zhangbb systemd[1]: Failed to start ProFTPD FTP Server.
Jan 16 14:51:48 zhangbb systemd[1]: Unit proftpd.service entered failed state.
Jan 16 14:51:48 zhangbb systemd[1]: proftpd.service failed.

[root@zhangbb ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core) 
Release:        7.6.1810
Codename:       Core

[root]# proftpd -V
Compile-time Settings:
  Version: 1.3.5e (maint)
  Platform: LINUX [Linux 3.10.0-693.11.6.el7.x86_64 x86_64]
  Built: Wed Jan 31 2018 16:32:29 UTC
  Built With:
    configure  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/run/proftpd' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--enable-ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--enable-pcre' '--enable-shadow' '--enable-tests' '--with-libraries=/usr/lib64/mysql' '--with-includes=/usr/include/mysql' '--with-modules=mod_readme:mod_auth_pam:mod_tls' '--with-shared=mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_ldap:mod_ban:mod_wrap:mod_ctrls_admin:mod_facl:mod_load:mod_vroot:mod_radius:mod_ratio:mod_rewrite:mod_site_misc:mod_exec:mod_shaper:mod_geoip:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_copy:mod_deflate:mod_ifversion:mod_qos:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_tls_shmcache:mod_tls_memcache:mod_ifsession' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic'

  CFLAGS: -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1  -m64 -mtune=generic -Wall
  LDFLAGS: -L$(top_srcdir)/lib -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/lib64/mysql -L/usr/lib64/mysql -L/usr/lib64
  LIBS: -lacl  -lpcreposix -lpcre -lssl -lcrypto -lssl -lcrypto -lcap  -lmemcached -lmemcachedutil  -lssl -lcrypto  -lpam -lsupp -lcrypt -ldl 

  Files:
    Configuration File:
      /etc/proftpd.conf
    Pid File:
      /run/proftpd/proftpd.pid
    Scoreboard File:
      /run/proftpd/proftpd.scoreboard
    Header Directory:
      /usr/include/proftpd
    Shared Module Directory:
      /usr/libexec/proftpd

  Features:
    - Autoshadow support
    + Controls support
    + curses support
    - Developer support
    + DSO support
    + IPv6 support
    + Largefile support
    - Lastlog support
    + Memcache support
    + ncursesw support
    + NLS support
    + OpenSSL support (FIPS enabled)
    + PCRE support
    + POSIX ACL support
    + Shadow file support
    + Sendfile support
    + Trace support

  Tunable Options:
    PR_TUNABLE_BUFFER_SIZE = 1024
    PR_TUNABLE_DEFAULT_RCVBUFSZ = 8192
    PR_TUNABLE_DEFAULT_SNDBUFSZ = 8192
    PR_TUNABLE_GLOBBING_MAX_MATCHES = 100000
    PR_TUNABLE_GLOBBING_MAX_RECURSION = 8
    PR_TUNABLE_HASH_TABLE_SIZE = 40
    PR_TUNABLE_NEW_POOL_SIZE = 512
    PR_TUNABLE_SCOREBOARD_BUFFER_SIZE = 80
    PR_TUNABLE_SCOREBOARD_SCRUB_TIMER = 30
    PR_TUNABLE_SELECT_TIMEOUT = 30
    PR_TUNABLE_TIMEOUTIDENT = 10
    PR_TUNABLE_TIMEOUTIDLE = 600
    PR_TUNABLE_TIMEOUTLINGER = 30
    PR_TUNABLE_TIMEOUTLOGIN = 300
    PR_TUNABLE_TIMEOUTNOXFER = 300
    PR_TUNABLE_TIMEOUTSTALLED = 3600
    PR_TUNABLE_XFER_SCOREBOARD_UPDATES = 10

**Comment by jlosito** [comment]
I had the same issue. What I did was remove the PidFile line in the service file and used the PidFile directive in the proftpd.conf file. This cleared the not readable statement for me.

**Comment by DJIronic** [comment]
Now I have the same issue, clear installation of pureFTP without touching the config on CentOS 7. 


```
 pure-ftpd.service - Pure-FTPd FTP server
   Loaded: loaded (/usr/lib/systemd/system/pure-ftpd.service; disabled; vendor preset: disabled)
   Active: active (running) since Thu 2019-06-06 21:20:03 UTC; 1s ago
  Process: 8605 ExecStart=/usr/sbin/pure-config.pl /etc/pure-ftpd/pure-ftpd.conf --daemonize (code=exited, status=0/SUCCESS)
 Main PID: 8606 (pure-ftpd)
   CGroup: /system.slice/pure-ftpd.service
           └─8606 pure-ftpd (SERVER)

Jun 06 21:20:03 ws1.saaznet.eu systemd[1]: Starting Pure-FTPd FTP server...
Jun 06 21:20:03 ws1.saaznet.eu systemd[1]: PID file /var/run/pure-ftpd.pid not readable (yet?) after start.
Jun 06 21:20:03 ws1.saaznet.eu systemd[1]: Started Pure-FTPd FTP server.

```

I am lost now, any idea?
