### ISSUE TITLE
SQLite concurrency issues

### ISSUE THREAD

**Issue by CTrox** [proftpd/proftpd#385]
### What I Did

We are using proftpd with sqlite as a backend. We have noticed some login failures and the following turned up in the sql.log:
```
mod_sql/4.3[5565]: error executing 'UPDATE accounts SET login_count=login_count+1, last_login=datetime('now') WHERE userid='user1'': (10) disk I/O error
mod_sql/4.3[5565]: message: 'disk I/O error'
```
We ran into this on a production server where a few logins could occur concurrently. I was able to reproduce by just doing some concurrent logins:

ftptest.sh
```bash
#!/bin/sh
HOST='hostname'
USER='user1'
PW='password'

ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PW
quit
END_SCRIPT

exit 0
```

EDIT: forgot this
```bash
# login 10 times using GNU parallel:
seq 10 | parallel -n0 ./ftptest.sh
```

### What I Expected/Wanted

Sqlite already has [locking](http://www.sqlite.org/lockingv3.html) mechanisms built in, maybe proftpd could handle this differently?

### ProFTPD Version and Configuration
Version 1.3.5rc3 (devel) from the Ubuntu 14.04 Package 1.3.5~rc3-2.1ubuntu2.1

sql config
```
<IfModule mod_sql.c>
MaxClients                      50 "sorry, too much users online... (%m)"
MaxClientsPerUser               20 "sorry, only 20 parallel connections allowed"
MaxClientsPerHost               20 "sorry, only 20 parallel connections allowed"

DefaultRoot ~

SQLBackend sqlite
SQLEngine On
SQLConnectInfo /path/to/database/db.sqlite3
SQLAuthenticate users
AuthOrder       mod_sql.c
SQLLogFile /var/log/proftpd/sql.log
SQLAuthTypes OpenSSL Crypt

SQLMinId 33
SQLDefaultUID 33
SQLDefaultGID 33

SQLNamedQuery get-user-by-name SELECT "userid, crypted_password, uid, gid, homedir, shell FROM accounts WHERE userid = '%U' AND deleted_at IS NULL"
SQLNamedQuery get-user-by-id SELECT "userid, crypted_password, uid, gid, homedir, shell FROM accounts WHERE uid = %{0} AND deleted_at IS NULL"
SQLUserInfo custom:/get-user-by-name/get-user-by-id

SQLLog PASS login
SQLNamedQuery login UPDATE "login_count=login_count+1, last_login=datetime('now') WHERE userid='%u'" accounts

SQLLog MKD,STOR,DELE,RNTO activity
SQLNamedQuery activity UPDATE "last_activity=datetime('now') WHERE userid='%u'" accounts

RootLogin Off
RequireValidShell off
</IfModule>
```

**Comment by Castaglia** [comment]
Thanks for the report!  I suspect that the contention will be caused by the `SQLLog PASS`  directive, for locking is really only needed on _writes_.  For experimenting, then, if possible I would recommend temporarily commenting out your `SQLLog PASS` configuration, to see if that changes the behavior

Introducing locking will also possibly add latency to the login process, of which your clients might be sensitive; just something to be aware of.

I'll see if I can work on a PR for this later today.

**Comment by CTrox** [comment]
Thanks for the fast reply! You are right, disabling the ```SQLLog PASS``` does work but in our case we need that data. So if you have any other solution that would be great.

**Comment by dup2** [comment]
Our experience is that sqlite is not suitable for multi-process environments accessing the same database. We had similar issues with web applications with a multi process model and, once you start getting a lot of concurrent sessions, suffered from  severe latency and timeouts when multiple processes try to lock the database concurrently.

I think similar constraints apply here, IMHO if you can, switch to PostgreSQL or similar.

**Comment by Castaglia** [comment]
Interesting.  I'm able to reproduce the issue locally, using the latest code.  Of particular interest is that when I _do_ see the "disk I/O error" reported, it is _always_ accompanied by an _earlier_ error message, about failing to set the `MEMORY` journal mode:
```
2017-01-12 04:06:01,809 mod_sql/4.3[4112]: error setting MEMORY journal mode: database is locked
2017-01-12 04:06:01,815 mod_sql/4.3[4112]: error executing 'UPDATE users SET login_count=login_count+1, last_login=datetime('now') WHERE userid='tj'': (10) disk I/O error
2017-01-12 04:06:01,815 mod_sql/4.3[4112]: unrecoverable backend error
2017-01-12 04:06:01,815 mod_sql/4.3[4112]: error: 'mod_sql_sqlite/0.4'
2017-01-12 04:06:01,815 mod_sql/4.3[4112]: message: 'disk I/O error'
```
Thus I am wondering if the root cause may be that that initial setting of the [journal mode](https://www.sqlite.org/pragma.html#pragma_journal_mode) `PRAGMA` fails, and thus for that session, in-memory journaling is *not* used -- and that greatly increases the risk/chances of database contention.

**Comment by Castaglia** [comment]
Since the PR has resolved the issue per my local tests, I'm going to merge it in (and backport the changes to the 1.3.5 branch).  Please let me know if this doesn't address things for you.
