### ISSUE TITLE
how can I completely turn off ftp

### ISSUE THREAD

**Issue by brotzeit** [proftpd/proftpd#822]
I only want to use SFTP and disable FTP for my proftp server. I don't want to "Limit LOGIN", but turn it off completely. I also tried to turn off the DefaultServer, but this way the server still answers.

What I want is the response "ftp: connect: Connection refused". How can I configure proftp this way ?

**Comment by Castaglia** [comment]
In order to achieve a "Connection refused" error message, then ProFTPD must not be listening on a TCP port _at all_.  That's just the way TCP connections work.  If that is the case, then ProFTPD cannot support either FTP _or SFTP_.  In other words, you cannot achieve your desired behavior, while still supporting SFTP.  The `<Limit LOGIN>` approach, as documented [here](http://www.proftpd.org/docs/contrib/mod_sftp.html#SFTPOnly), is what you need to use.

**Comment by brotzeit** [comment]
Ok. Thanks for the quick response.

**Comment by devfaz** [comment]
HI @Castaglia - looks like you didnt understand the question. @brotzeit tries to configure proftpd, so he is *not* listening on port 21 for ftp, instead it should only answer requests on a separate *sftp-port*. ProFTPd is able to do this by disabling the FTP-Port

`Port 0`

and configuring a separate SFTP-Port as described in the docs.

**Comment by brotzeit** [comment]
Side note: Non integer values for the FTP port also result in "0".

**Comment by Elias481** [comment]
I think there another way that for me looks more clean: just disable the default server (DefaultServer off) and create vhost(s) for the services you want to offer.
